server:
    # Add valid YAML mapping here
    port: 8081
    error:
        include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: muhammad.23
    url: jdbc:mysql://localhost:3306/sei_proyek
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true